# -*- coding: utf-8 -*-
"""三类视觉审核 POC 样本：只用于流程验证，不代表真实模型输出。"""
from __future__ import annotations

from typing import Any, Dict, List


VISUAL_REVIEW_CASES: List[Dict[str, Any]] = [
    {
        "case_id": "video_unboxing_pass",
        "scenario": "video_unboxing",
        "title": "开箱视频材料完整",
        "model_signals": {
            "one_take": True,
            "six_sides": True,
            "cut_detected": False,
            "item_left_frame": False,
            "waybill_visible": True,
            "defect_visible": True,
            "confidence": 0.91,
            "evidence": "连续开箱视频，面单、商品六面、划痕位置均可见",
        },
        "expected": "pass",
    },
    {
        "case_id": "video_unboxing_cut",
        "scenario": "video_unboxing",
        "title": "开箱视频疑似剪辑",
        "model_signals": {
            "one_take": False,
            "six_sides": True,
            "cut_detected": True,
            "item_left_frame": False,
            "waybill_visible": True,
            "defect_visible": True,
            "confidence": 0.76,
            "evidence": "中途出现跳帧，无法确认商品是否全程在画面内",
        },
        "expected": "suspect",
    },
    {
        "case_id": "video_unboxing_invalid",
        "scenario": "video_unboxing",
        "title": "开箱视频证据无效",
        "model_signals": {
            "one_take": False,
            "six_sides": False,
            "cut_detected": True,
            "item_left_frame": True,
            "waybill_visible": False,
            "defect_visible": False,
            "confidence": 0.62,
            "evidence": "视频缺少面单和六面展示，商品中途离开画面",
        },
        "expected": "fail",
    },
    {
        "case_id": "video_unboxing_low_confidence",
        "scenario": "video_unboxing",
        "title": "开箱视频低置信度需人工",
        "model_signals": {
            "one_take": True,
            "six_sides": True,
            "cut_detected": False,
            "item_left_frame": False,
            "waybill_visible": True,
            "defect_visible": False,
            "confidence": 0.59,
            "evidence": "视频连续但瑕疵位置过暗，模型无法稳定判断",
        },
        "expected": "manual_review",
    },
    {
        "case_id": "product_damage_pass",
        "scenario": "product_damage",
        "title": "商品有伤照片清晰",
        "model_signals": {
            "damage_visible": True,
            "damage_area": "吧唧正面右下角",
            "damage_type": "明显划痕",
            "damage_severity": "light",
            "blurred": False,
            "reflection_blocked": False,
            "package_context_visible": True,
            "confidence": 0.89,
            "evidence": "瑕疵区域清晰，商品与包装同框",
        },
        "expected": "pass",
    },
    {
        "case_id": "product_damage_severe",
        "scenario": "product_damage",
        "title": "商品严重破损照片清晰",
        "model_signals": {
            "damage_visible": True,
            "damage_area": "亚克力立牌左侧边缘",
            "damage_type": "断裂",
            "damage_severity": "heavy",
            "blurred": False,
            "reflection_blocked": False,
            "package_context_visible": True,
            "confidence": 0.93,
            "evidence": "破损位置清晰，商品与包装同框",
        },
        "expected": "pass",
    },
    {
        "case_id": "product_damage_unclear",
        "scenario": "product_damage",
        "title": "商品有伤照片无法判定",
        "model_signals": {
            "damage_visible": False,
            "damage_area": "",
            "damage_type": "",
            "damage_severity": "",
            "blurred": True,
            "reflection_blocked": True,
            "package_context_visible": False,
            "confidence": 0.58,
            "evidence": "图片模糊且反光遮挡，无法定位瑕疵",
        },
        "expected": "manual_review",
    },
    {
        "case_id": "minor_material_complete",
        "scenario": "minor_material",
        "title": "未成年人资料较完整",
        "model_signals": {
            "guardian_statement_present": True,
            "minor_identity_present": True,
            "order_ownership_match": True,
            "payment_proof_present": True,
            "sensitive_info_masked": True,
            "tamper_suspected": False,
            "confidence": 0.86,
            "evidence": "监护说明、订单归属、付款证明齐全，敏感信息已遮盖",
        },
        "expected": "manual_review",
    },
    {
        "case_id": "minor_material_tampered",
        "scenario": "minor_material",
        "title": "未成年人资料疑似篡改",
        "model_signals": {
            "guardian_statement_present": True,
            "minor_identity_present": True,
            "order_ownership_match": False,
            "payment_proof_present": True,
            "sensitive_info_masked": True,
            "tamper_suspected": True,
            "confidence": 0.82,
            "evidence": "监护说明与付款流水姓名不一致，材料边缘存在疑似拼接痕迹",
            "ocr_text": "监护人 张*；手机号 138****1234；证件号 110***********1234",
        },
        "expected": "manual_review",
    },
    {
        "case_id": "minor_material_missing",
        "scenario": "minor_material",
        "title": "未成年人资料缺失",
        "model_signals": {
            "guardian_statement_present": False,
            "minor_identity_present": True,
            "order_ownership_match": False,
            "payment_proof_present": False,
            "sensitive_info_masked": False,
            "tamper_suspected": False,
            "confidence": 0.73,
            "evidence": "缺少监护说明和付款证明，且未完成敏感信息遮盖",
        },
        "expected": "request_more_material",
    },
]
